-- Supabase setup note
-- -------------------
-- `db/schema.sql` is the canonical VISR schema.
--
-- To set up Supabase after pulling integration work:
-- 1. Open the Supabase SQL Editor.
-- 2. Run the full contents of `db/schema.sql`.
-- 3. Optionally run `db/seed.sql` for showcase daily-flow data.
--
-- This file intentionally points to the canonical schema instead of duplicating
-- table definitions that can drift.
